import os

import pandas as pd
import yaml

# --- Config ------------------------------------------------------------------

configfile: "config/config.yaml"

# --- Resolved parameters (generated by scripts/auto_params.py) ---------------

_resolved_path = "config/resolved_params.yaml"
if not os.path.exists(_resolved_path):
    raise WorkflowError(
        f"'{_resolved_path}' not found.\n"
        "Generate it first:\n"
        "  python scripts/auto_params.py --samples config/samples.tsv"
    )
with open(_resolved_path) as _fh:
    RESOLVED = yaml.safe_load(_fh)


# --- Auto-tuner knob resolver ------------------------------------------------
# A rule reads its per-job thread/engine knobs through this: an explicit value in
# config wins (a user pin), while the sentinel 'auto' (or an absent key) defers to
# the host-tuned value in resolved_params.yaml (scripts/auto_params.py), then the
# hard default. Keeps the published config self-tuning yet fully overridable.
def _auto(cfg_value, resolved_key, default):
    if cfg_value is None or (
        isinstance(cfg_value, str) and cfg_value.strip().lower() == "auto"
    ):
        return RESOLVED.get(resolved_key, default)
    return cfg_value

# --- Container specs (config/containers.yaml) --------------------------------

_containers_path = "config/containers.yaml"
if not os.path.exists(_containers_path):
    raise WorkflowError(f"'{_containers_path}' not found.")
with open(_containers_path) as _fh:
    CONTAINERS = yaml.safe_load(_fh)

# --- Sample table ------------------------------------------------------------

samples_df = pd.read_csv(config["samples"], sep="\t", dtype=str)

# Detect input schema from the columns. The bam schema (sample_id, bam) drives
# external-alignment ingest; the fastq schema (sample_id, readgroup, fq1, fq2)
# drives the FASTQ→CRAM mapping pipeline. SCHEMA selects which rules file the
# Snakefile includes and which helpers below are exercised.
if "bam" in samples_df.columns and "fq1" not in samples_df.columns:
    SCHEMA = "bam"
    # One row per sample_id; do NOT index by readgroup (bam has none).
    samples_df = samples_df.set_index("sample_id", drop=False)
else:
    SCHEMA = "fastq"
    samples_df = samples_df.set_index(["sample_id", "readgroup"], drop=False)

SAMPLES = samples_df["sample_id"].unique().tolist()

REF = config["ref"]["fasta"]

# --- Chromosomes for scatter-gather (calling stage) --------------------------

_calling_cfg = config.get("calling", {})
CHROMOSOMES = _calling_cfg.get("chromosomes", [])

# --- Ingest helpers (bam schema) ---------------------------------------------

def get_external_alignment(wildcards):
    """Return the external BAM/CRAM path for a sample (bam schema only)."""
    return samples_df.loc[wildcards.sample, "bam"]


# --- Mapping helpers (fastq schema) ------------------------------------------

def get_fastqs(wildcards):
    """Return fq1, fq2 for a given sample + readgroup."""
    row = samples_df.loc[(wildcards.sample, wildcards.rg)]
    return {"fq1": row["fq1"], "fq2": row["fq2"]}


def get_readgroups(sample):
    """Return list of readgroups for a sample."""
    return samples_df.loc[sample, "readgroup"].unique().tolist()


def get_sorted_bams(wildcards):
    """Return all sorted BAMs for a sample (one per readgroup)."""
    rgs = get_readgroups(wildcards.sample)
    return expand(
        "results/mapping/{sample}/align/{sample}.{rg}.sorted.bam",
        sample=wildcards.sample,
        rg=rgs,
    )

# --- BQSR helpers -----------------------------------------------------------

def get_scattered_recal_tables(wildcards):
    """Return per-chromosome recalibration tables for a sample."""
    return expand(
        "results/mapping/{sample}/bqsr_scatter/{chrom}.recal.table",
        sample=wildcards.sample,
        chrom=CHROMOSOMES,
    )


# --- Calling helpers ---------------------------------------------------------

def get_scattered_vcfs(wildcards):
    """Return per-chromosome raw VCFs for a sample."""
    return expand(
        "results/calling/{sample}/scatter/{chrom}.vcf.gz",
        sample=wildcards.sample,
        chrom=CHROMOSOMES,
    )


def get_scattered_stats(wildcards):
    """Return per-chromosome Mutect2 stats files for a sample."""
    return expand(
        "results/calling/{sample}/scatter/{chrom}.vcf.gz.stats",
        sample=wildcards.sample,
        chrom=CHROMOSOMES,
    )


def get_scattered_f1r2(wildcards):
    """Return per-chromosome f1r2 tar.gz files for a sample."""
    return expand(
        "results/calling/{sample}/scatter/{chrom}.f1r2.tar.gz",
        sample=wildcards.sample,
        chrom=CHROMOSOMES,
    )
