import os

import pandas as pd
import yaml

# --- Config ------------------------------------------------------------------

configfile: "config/config.yaml"

# --- Resolved parameters (generated by scripts/auto_params.py) ---------------

_resolved_path = "config/resolved_params.yaml"
if not os.path.exists(_resolved_path):
    raise WorkflowError(
        f"'{_resolved_path}' not found.\n"
        "Generate it first:\n"
        "  python scripts/auto_params.py --samples config/samples.tsv"
    )
with open(_resolved_path) as _fh:
    RESOLVED = yaml.safe_load(_fh)

# --- Container specs (config/containers.yaml) --------------------------------

_containers_path = "config/containers.yaml"
if not os.path.exists(_containers_path):
    raise WorkflowError(f"'{_containers_path}' not found.")
with open(_containers_path) as _fh:
    CONTAINERS = yaml.safe_load(_fh)

# --- Sample table ------------------------------------------------------------

samples_df = pd.read_csv(config["samples"], sep="\t", dtype=str)
samples_df = samples_df.set_index(["sample_id", "readgroup"], drop=False)

SAMPLES = samples_df["sample_id"].unique().tolist()

REF = config["ref"]["fasta"]

# --- Chromosomes for scatter-gather (calling stage) --------------------------

_calling_cfg = config.get("calling", {})
CHROMOSOMES = _calling_cfg.get("chromosomes", [])

# --- Mapping helpers ---------------------------------------------------------

def get_fastqs(wildcards):
    """Return fq1, fq2 for a given sample + readgroup."""
    row = samples_df.loc[(wildcards.sample, wildcards.rg)]
    return {"fq1": row["fq1"], "fq2": row["fq2"]}


def get_readgroups(sample):
    """Return list of readgroups for a sample."""
    return samples_df.loc[sample, "readgroup"].unique().tolist()


def get_sorted_bams(wildcards):
    """Return all sorted BAMs for a sample (one per readgroup)."""
    rgs = get_readgroups(wildcards.sample)
    return expand(
        "results/mapping/{sample}/align/{sample}.{rg}.sorted.bam",
        sample=wildcards.sample,
        rg=rgs,
    )

# --- Calling helpers ---------------------------------------------------------

def get_scattered_vcfs(wildcards):
    """Return per-chromosome raw VCFs for a sample."""
    return expand(
        "results/calling/{sample}/scatter/{chrom}.vcf.gz",
        sample=wildcards.sample,
        chrom=CHROMOSOMES,
    )


def get_scattered_stats(wildcards):
    """Return per-chromosome Mutect2 stats files for a sample."""
    return expand(
        "results/calling/{sample}/scatter/{chrom}.vcf.gz.stats",
        sample=wildcards.sample,
        chrom=CHROMOSOMES,
    )


def get_scattered_f1r2(wildcards):
    """Return per-chromosome f1r2 tar.gz files for a sample."""
    return expand(
        "results/calling/{sample}/scatter/{chrom}.f1r2.tar.gz",
        sample=wildcards.sample,
        chrom=CHROMOSOMES,
    )
